### ISSUE TITLE
Bug: Popout Menus in Darkmode

### ISSUE THREAD

**Issue by devilAPI** [LinwoodCloud/dev_doctor#13]
In Darkmode, the Buttons are purple, thats kind of hard to read on darkmode

**Comment by strifel** [comment]
![Bildschirmfoto 2021-02-10 um 09 35 24](https://user-images.githubusercontent.com/24608706/107484859-4e17c300-6b83-11eb-9ee7-ccc8c60464c8.png)

**Comment by devilAPI** [comment]
Great!
