### ISSUE TITLE
Suggestion: Add RSS Support, would be great

### ISSUE THREAD

**Issue by devilAPI** [LinwoodCloud/dev_doctor#20]
Add RSS Support, there are already many sites with RSS Support out there, would be great so COntent Providers, that are already using RSS dont have to migrate hundreds of articles to a dev_doc like backend

**Comment by CodeDoctorDE** [comment]
There is already a rss support. You can reach it on https://linwood.tk/blog/rss.xml and https://linwood.tk/blog/atom.xml.

**Comment by devilAPI** [comment]
well if there is, it dosent work :/ when adding `https://linwood.tk/blog/rss.xml` , i get this Error:

`Error: NoSuchMethodError: method not found: 'xT' on null`

**Comment by CodeDoctorDE** [comment]
Try  https://linwood.tk/blog/atom.xml

**Comment by devilAPI** [comment]
I did, same error

**Comment by CodeDoctorDE** [comment]
I tried it on https://rssatom.de/ and everything works with the atom.xml

**Comment by devilAPI** [comment]
then dev_doc is broken?

**Comment by CodeDoctorDE** [comment]
![image](https://user-images.githubusercontent.com/20452814/107504935-4add0100-6b9c-11eb-9cf8-244234a483eb.png)
I see the news.

**Comment by devilAPI** [comment]
But thats not what i meant, i was asking for Text-Only-courses, in RSS, so content creators dont have to migrate their existing articles

**Comment by CodeDoctorDE** [comment]
Okay, that's another idea. I will add it to my todo list

**Comment by CodeDoctorDE** [comment]
Do you have any example for a rss?

**Comment by devilAPI** [comment]
No, sorry
