### ISSUE TITLE
Suggestion: Desktop Support

### ISSUE THREAD

**Issue by devilAPI** [LinwoodCloud/dev_doctor#31]
https://flutter.dev/desktop

**Comment by devilAPI** [comment]
`flutter config --enable-windows-desktop`

**Comment by CodeDoctorDE** [comment]
I need to wait until the webview plugin is available for desktop: https://github.com/pichillilorenzo/flutter_inappwebview/issues/460

**Comment by devilAPI** [comment]
Wich parts of dev_doc is even use that? I've never seen a Webpage in the App? Maybe its not important, and can be removed

**Comment by CodeDoctorDE** [comment]
It's the video part item. Maybe I can replace it with a link to the page?!

**Comment by CodeDoctorDE** [comment]
next release: desktop support :)

**Comment by devilAPI** [comment]
i love flutter 2.

**Comment by CodeDoctorDE** [comment]
it's now in beta ❤️ 
i will add a button to open the video it in the browser on desktop

**Comment by CodeDoctorDE** [comment]
https://github.com/flutter/flutter/issues/14967
is the next target platform :)

**Comment by devilAPI** [comment]
i really dont see UWP Flutter Support. There's no way of Material Design in UWP. It's probably faster to create a completely new dev_doctor application for UWP. UWP is just not feature-rich enough.

**Comment by CodeDoctorDE** [comment]
I think this isn't a design question. If we have up support, we can use the same codespace

**Comment by devilAPI** [comment]
I dont think UWP Flutter is a real thing. They're probably not implementing this.
