### ISSUE TITLE
Documentation: "Linwood promotes closed-source network services"

### ISSUE THREAD

**Issue by Glitchy-Tozier** [LinwoodCloud/dev_doctor#43]
**Describe the bug**
(It's a warning in F-Droid)
Why is this the case?

**Screenshots**
![Screenshot_20210227-080755_F-Droid.jpg](https://user-images.githubusercontent.com/59611881/109378461-0dce7980-78d3-11eb-81df-33dfcc1f5fc3.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: Android 10
 - Browser: ...Fdroid
 - Version: 1.0.0

**Comment by CodeDoctorDE** [comment]
I think it's because I use youtube in the sample course. But you can use normal video files too :/

**Comment by CodeDoctorDE** [comment]
Do you know how can I change this?

**Comment by Glitchy-Tozier** [comment]
Unfortunately, I have no idea. It's probably best to contact some of the F-Droid people.

**Comment by CodeDoctorDE** [comment]
because of this, i added this course not to the default...

**Comment by CodeDoctorDE** [comment]
https://gitlab.com/fdroid/fdroiddata/-/issues/2314

**Comment by CodeDoctorDE** [comment]
Should be fixed!

**Comment by CodeDoctorDE** [comment]
It's fixed: https://www.f-droid.org/en/packages/com.github.linwoodcloud.dev_doctor/
