### ISSUE TITLE
Suggestion: Prevent embed videos from being downloaded

### ISSUE THREAD

**Issue by moshpirit** [LinwoodCloud/dev_doctor#45]

**Comment by CodeDoctorDE** [comment]
That's the normal context menu if you embed a nomral video. I don't know if I can prevent this with iframes or if I want. It should be an open learning platform and this prevention may restrict that

**Comment by moshpirit** [comment]
So the idea is that every person should be able to attend any course?

**Comment by CodeDoctorDE** [comment]
Yeah, you got it! Education should have everyone

**Comment by moshpirit** [comment]
I agree, and I see then that what I was asking then has no sense in this project, which I guess requires funding so people have incentives to come and share their knowledge (like in public schools where teachers are paid by the rest of the citizens through the Government).

**Comment by CodeDoctorDE** [comment]
Yes, but no problem :)
We have a discord if you have further questions: https://discord.linwood.dev
